version: '3.8'

services:
  postgres_db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=agunpass
      - POSTGRES_DB=predictions_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - backend

  model_service:
    image: project_model_service
    build:
      context: ./model_service
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    networks:
      - backend

  streamlit_app:
    image: project_streamlit_app
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - model_service
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge
